name: audiobookshelf
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - 13378:80
    volumes:
      - /home/danny/media/audiobooks:/audiobooks
      - /home/danny/media/books:/books
      - /home/danny/media/podcasts:/podcasts
      - /home/danny/media/audiobookshelf/config:/config
      - /home/danny/media/audiobookshelf/metadata:/metadata
    environment:
      - TZ=America/Chicago
      - ALLOW_FRAME=1
  abs-tract:
      container_name: abs-tract
      ports:
         - 5555:5555
      restart: unless-stopped
      image: arranhs/abs-tract:latest
