services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - ND_ENABLEGRAVATAR=true
      - ND_ENABLESHARING=true
      - ND_DEFAULTTHEME=Catppuccin Macchiato
      - ND_SPOTIFY_ID=${ND_SPOTIFY_ID}
      - ND_SPOTIFY_SECRET=${ND_SPOTIFY_SECRET}
      - ND_LASTFM_APIKEY=${ND_LASTFM_APIKEY}
      - ND_LASTFM_SECRET=${ND_LASTFM_SECRET}
      #- ND_SCANSCHEDULE=1h
      #- ND_SCANNER_GROUPALBUMRELEASES=true
    volumes:
      - /home/danny/media/navidrome:/data
      - /home/danny/media/music:/music:ro
    ports:
      - 4533:4533
    restart: unless-stopped
networks: {}
